worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;

    upstream nodeflix-cluster { 
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;
        server 127.0.0.1:5003;
    }

    server {
        listen 5000;
        server_name localhost;

        location / {
            proxy_pass http://nodeflix-cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }
    }
}

